<?php
/**
 * @file
 *
 * Main module code for Socrata Views
 */

/**
 * Implements hook_views_api
 */
function socrata_views_views_api() {
  return array(
    'api' => 3.0,
  );
}

/**
 * Implements hook_views_plugins().
 */
function socrata_views_views_plugins() {
  $path = drupal_get_path('module', 'socrata_views');

  $style_defaults = array(
    'path' => $path . '/plugins',
    'parent' => 'socrata_views',
    'uses row plugin' => FALSE,
    'uses fields' => TRUE,
    'uses options' => TRUE,
    'type' => 'socrata_export',
  );

  $plugins = array(
    'module' => 'socrata_views',
    'query' => array(
      'socrata_query' => array(
        'title' => t('Socrata Query'),
        'help' => t('Query will be run using the Socrata SODA API.'),
        'handler' => 'socrata_views_plugin_query',
        'parent' => 'views_plugin_query',
      ),
    ),
    'display' => array(
      'socrata_data_export' => array(
        'title' => t('Socrata data export'),
        'help' => t('Query will be run using the Socrata SODA API.'),
        'handler' => 'socrata_views_plugin_display_export',
        'parent' => 'views_plugin_display_feed',
        'type' => 'socrata_export',
        'use pager' => FALSE,
      ),
    ),
    'style' => array(
      'socrata_views' => array(
        // this isn't really a display but is necessary so the file can
        // be included.
        'no ui' => TRUE,
        'handler' => 'socrata_views_plugin_style_export',
        'path' => $path . '/plugins',
        'type' => 'normal',
      ),
      'socrata_views_csv' => array(
        'title' => t('CSV file'),
        'help' => t('Display the view as a comma separated list.'),
        'handler' => 'socrata_views_plugin_style_export',
        'export feed type' => 'csv',
        'export feed text' => 'CSV',
        // 'export feed file' => '%view.csv',
        // 'export feed icon' => drupal_get_path('module', 'socrata_views') . '/images/csv.png',
      ) + $style_defaults,
      'socrata_views_json' => array(
        'title' => t('JSON file'),
        'help' => t('Display the view as a txt file.'),
        'handler' => 'socrata_views_plugin_style_export',
        'export feed type' => 'json',
        'export feed text' => 'JSON',
        // 'export feed file' => '%view.json',
        // 'export feed icon' => drupal_get_path('module', 'socrata_views') . '/images/json.png',
      ) + $style_defaults,
    ),
  );

  return $plugins;
}
